### PR TITLE
Improve configuration definition

### PR DESCRIPTION
**Pull request by bobvandevijver**
This allows you to use the new php based configuration without hassle:

```php
return static function(ImapConfig $imap): void
{
	$imap->connection('some_connection')
	     ->mailbox('a_mailbox');
	$imap->connection('second_connection')
	     ->mailbox('another_mailbox');
};
```

### CODE REVIEW

**Comment by ThomasLandauer** [comment]
@secit-pl This works for me (Symfony 6.2.1), could you please merge it?

**Comment by secit-pl** [comment]
@bobvandevijver I understand the pull request changes but I do not understand your example. What is ImapConfig? It looks like it's not a part of this bundle.

**Comment by bobvandevijver** [comment]
@secit-pl ImapConfig is being generated automatically by Symfony based on the bundle configuration, which has been introduced with Symfony 5.3. See this blogpost for some more information: https://symfony.com/blog/new-in-symfony-5-3-config-builder-classes.

**Comment by secit-pl** [comment]
Thanks, had to miss this blog post. Merged.

**Pull request merged**
