### PR TITLE
feat: drop support for symfony 4, add support for symfony 7,

### PR DESCRIPTION
**Pull request by Chris53897**
add missing symfony/console to composer.json

### CODE REVIEW

**Comment by ThomasLandauer** [comment]
@secit-pl This is more urgent now, since Symfony 7.0 was released already.

**Comment by ownede** [comment]
@secit-pl please take a look

**Comment by ryckblick** [comment]
@secit-pl a merge would be highly appreciated

**Comment by Chris53897** [comment]
@secit-pl friendly ping

**Comment by secit-pl** [comment]
The new bundle version 3.0.0 was released with Symfony 7 support. Due to refactored code incompatibility the PR cannot be merged.

Caution: please read the migration guide at the end of the documentation before migrating from version 2.x to 3.x.

**Pull request closed without merging**
